# fly.toml app configuration file generated for hominio-app-api
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'hominio-api'
primary_region = 'fra'

[build]

[env]
PORT = '4204'
NODE_ENV = 'production'

[http_service]
internal_port = 4204
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1  # Keep API service always running

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

