name: Deploy Next (maia + moai)

on:
  push:
    branches: [next]
  workflow_dispatch:

jobs:
  deploy-moai:
    name: Deploy moai
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: Deploy moai
        run: ./services/moai/deploy.sh

  deploy-maia:
    name: Deploy maia
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: Deploy maia
        run: ./services/maia/deploy.sh
